(() => {
  "use strict";
  if(window.__ogxDashboard)return;window.__ogxDashboard=true;
  const origin=location.origin,prefixes=[`ogxIntel:${origin}:`,`ogxStats:${origin}:`,`ogxOwn:${origin}:`,`ogxReport:${origin}:`],eventsKey=`ogxEvents:${origin}`,watchKey=`ogxWatch:${origin}`;
  const host=document.createElement('div'),root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>:host{font:13px/1.45 Arial;color:#e7f4ff}button,input,select{font:inherit;padding:7px;color:#fff;background:#18334b;border:1px solid #527893;border-radius:5px}button{cursor:pointer}#open{position:fixed;left:300px;bottom:16px;z-index:2147483646}#box{position:fixed;inset:5vh 5vw;z-index:2147483647;background:#0e1b29;border:1px solid #628ba6;border-radius:10px;padding:16px;overflow:auto;box-shadow:0 12px 70px #000c}#close{float:right}.tabs{display:flex;gap:5px;flex-wrap:wrap}.tab{margin-top:14px}.card{background:#14283a;padding:10px;margin:7px 0;border-radius:6px;border-left:3px solid #4eb2df}.muted{color:#a9bed0;font-size:11px}.good{color:#8be28b}.bad{color:#ff9696}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #314c61;text-align:left}[hidden]{display:none!important}</style>
  <button id="open">Kontrol merkezi</button><section id="box" hidden><button id="close">Kapat</button><h2>OGameX Kontrol Merkezi v1.0</h2><div class="tabs"><button data-tab="targets">Takip</button><button data-tab="events">Değişiklikler</button><button data-tab="reports">Keşif raporları</button><button data-tab="resources">Kaynaklar</button><button data-tab="backup">Yedekleme</button></div><div id="view" class="tab"></div></section>`;
  document.documentElement.append(host);const $=id=>root.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function data(){return chrome.storage.local.get(null);}function rows(all,prefix){return Object.entries(all).filter(([k])=>k.startsWith(prefix)).map(([,v])=>v);}
  async function targets(){const all=await data(),intel=rows(all,prefixes[0]),stats=rows(all,prefixes[1]),watch=all[watchKey]||{};const players=new Map();[...intel,...stats].forEach(r=>{if(r.playerId)players.set(r.playerId,r.player||players.get(r.playerId)?.player||'Oyuncu');});$('view').innerHTML=`<p>Bir oyuncuyu takip ettiğinde değişiklikleri geçmişte tutulur. Yalnızca taranan/ziyaret edilen veriler karşılaştırılır.</p><input id="filter" placeholder="Oyuncu ara"><div id="players"></div>`;const draw=()=>{const q=$('filter').value.toLocaleLowerCase('tr-TR');$('players').innerHTML=[...players].filter(([,n])=>n.toLocaleLowerCase('tr-TR').includes(q)).sort((a,b)=>a[1].localeCompare(b[1],'tr')).map(([id,n])=>{const planets=intel.filter(x=>x.playerId===id).length,last=stats.filter(x=>x.playerId===id).sort((a,b)=>b.at-a.at)[0];return `<div class="card"><button data-watch="${id}">${watch[id]?'★ Takipten çıkar':'☆ Takip et'}</button> <strong>${esc(n)}</strong> — ${planets} bilinen gezegen<div class="muted">${last?`Son istatistik: ${esc(last.category)} ${last.value.toLocaleString('tr-TR')} • ${new Date(last.at).toLocaleString('tr-TR')}`:'İstatistik okunmadı'}</div></div>`}).join('')||'<p>Kayıtlı oyuncu yok.</p>';};draw();$('filter').addEventListener('input',draw);$('players').addEventListener('click',async e=>{const id=e.target.dataset.watch;if(!id)return;if(watch[id])delete watch[id];else watch[id]={id,name:players.get(id),at:Date.now()};await chrome.storage.local.set({[watchKey]:watch});targets();});}
  async function events(){const all=await data(),watch=all[watchKey]||{},items=(all[eventsKey]||[]).filter(x=>!x.playerId||!Object.keys(watch).length||watch[x.playerId]).sort((a,b)=>b.at-a.at);$('view').innerHTML=`<p>${items.length} kayıt (en yeni üstte).</p>`+items.slice(0,300).map(x=>`<div class="card"><strong>${esc(x.player||x.kind)}</strong> ${x.coords?`[${esc(x.coords)}]`:''}<div>${x.changes?x.changes.map(c=>`${esc(c.label)}: ${esc(c.before)} → ${esc(c.after)}`).join('<br>'):`${esc(x.category)}: ${Number(x.delta)>0?'+':''}${Number(x.delta).toLocaleString('tr-TR')}`}</div><div class="muted">${new Date(x.at).toLocaleString('tr-TR')}</div></div>`).join('')||'<p>Henüz değişiklik yok.</p>';}
  async function reports(){const all=await data(),list=rows(all,prefixes[3]).sort((a,b)=>b.at-a.at),sum=k=>list.reduce((n,r)=>n+(r[k]||0),0),types={};list.forEach(r=>types[r.type]=(types[r.type]||0)+1);$('view').innerHTML=`<div class="card"><strong>${list.length} keşif raporu</strong><br>Metal ${sum('metal').toLocaleString('tr-TR')} • Kristal ${sum('crystal').toLocaleString('tr-TR')} • Döteryum ${sum('deuterium').toLocaleString('tr-TR')} • Karanlık madde ${sum('darkMatter').toLocaleString('tr-TR')}<div class="muted">${Object.entries(types).map(x=>x.join(': ')).join(' • ')||'Mesajlar sayfasında görülen rapor yok'}</div></div>`+list.slice(0,100).map(r=>`<div class="card"><strong>${esc(r.type)}</strong> — ${esc(r.summary)}<div class="muted">${new Date(r.at).toLocaleString('tr-TR')}</div></div>`).join('');}
  async function resources(){const all=await data(),list=rows(all,prefixes[2]).sort((a,b)=>String(a.coords).localeCompare(String(b.coords),undefined,{numeric:true})),sum=k=>list.reduce((n,r)=>n+(r[k]||0),0),cell=(r,k)=>{const x=r.resourceInfo?.[k],pct=x?.capacity?Math.min(100,r[k]/x.capacity*100):null,hours=x?.hourly>0&&x.capacity>r[k]?(x.capacity-r[k])/x.hourly:null;return `${r[k].toLocaleString('tr-TR')}${pct===null?'':`<div class="muted">%${pct.toFixed(1)}${hours===null?'':` • ~${hours.toFixed(1)} sa`}</div>`}`;};$('view').innerHTML=`<div class="card">Kayıtlı toplam: Metal ${sum('metal').toLocaleString('tr-TR')} • Kristal ${sum('crystal').toLocaleString('tr-TR')} • Döteryum ${sum('deuterium').toLocaleString('tr-TR')}<div class="muted">Farklı zamanlarda alınmış son kayıtlardır. Üretim ve kapasite okunabildiyse doluluk ile tahmini dolma süresi gösterilir.</div></div><table><tr><th>Gezegen</th><th>Metal</th><th>Kristal</th><th>Döteryum</th><th>Kayıt</th></tr>${list.map(r=>`<tr><td>${esc(r.name)} [${esc(r.coords)}]</td><td>${cell(r,'metal')}</td><td>${cell(r,'crystal')}</td><td>${cell(r,'deuterium')}</td><td>${new Date(r.at).toLocaleString('tr-TR')}</td></tr>`).join('')}</table>`;}
  async function backup(){const all=await data(),count=Object.keys(all).filter(k=>prefixes.some(p=>k.startsWith(p))||[eventsKey,watchKey,'ogxLogs'].includes(k)).length;$('view').innerHTML=`<p>${count} veri grubu yedeklenebilir.</p><button id="download">Tüm OGX verisini indir</button> <button id="restore">Yedekten geri yükle</button> <input id="file" type="file" accept="application/json" hidden> <button id="clean">90 günden eski geçmişi temizle</button><p id="result"></p>`;$('download').onclick=async()=>{const d=await data(),out=Object.fromEntries(Object.entries(d).filter(([k])=>k.startsWith('ogx'))),url=URL.createObjectURL(new Blob([JSON.stringify({version:1,origin,exportedAt:Date.now(),data:out},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`ogamex-yedek-${location.hostname}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};$('restore').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const parsed=JSON.parse(await $('file').files[0].text());if(parsed.version!==1||parsed.origin!==origin||!parsed.data||typeof parsed.data!=='object')throw new Error('Bu sunucuya ait geçerli yedek değil.');if(!confirm(`${Object.keys(parsed.data).length} kayıt geri yüklensin mi?`))return;await chrome.storage.local.set(parsed.data);$('result').textContent='Yedek geri yüklendi.';}catch(e){$('result').textContent=e.message;}};$('clean').onclick=async()=>{if(!confirm('90 günden eski olay ve rapor kayıtları silinsin mi?'))return;const d=await data(),cut=Date.now()-90*864e5,remove=Object.entries(d).filter(([k,v])=>k.startsWith(prefixes[3])&&v.at<cut).map(([k])=>k),events=(d[eventsKey]||[]).filter(x=>x.at>=cut);await chrome.storage.local.remove(remove);await chrome.storage.local.set({[eventsKey]:events});$('result').textContent=`${remove.length} eski rapor temizlendi.`;};}
  async function show(name){({targets,events,reports,resources,backup}[name]||targets)();}
  $('open').onclick=()=>{$('box').hidden=false;show('targets');};$('close').onclick=()=>{$('box').hidden=true;};root.querySelector('.tabs').onclick=e=>{if(e.target.dataset.tab)show(e.target.dataset.tab);};
})();
